#ifndef FUNNYOS_KERNEL_PROCESS_LAYOUT_H
#define FUNNYOS_KERNEL_PROCESS_LAYOUT_H

#include "../common/types.h"

#define PROCESS_ABI_REGION_START ((uintptr_t)0x0000008000000000ull)
#define PROCESS_ABI_REGION_END ((uintptr_t)0x0000008000100000ull)
#define PROCESS_ABI_STACK_SIZE 65536u
#define PROCESS_ABI_STACK_TOP PROCESS_ABI_REGION_END
#define PROCESS_ABI_STACK_BASE (PROCESS_ABI_STACK_TOP - PROCESS_ABI_STACK_SIZE)
#define PROCESS_ABI_STACK_GAP 4096u
#define PROCESS_ABI_IMAGE_BASE PROCESS_ABI_REGION_START
#define PROCESS_ABI_IMAGE_LIMIT (PROCESS_ABI_STACK_BASE - PROCESS_ABI_STACK_GAP)

#endif
